// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.BreakpointNotifier
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-BreakpointNotifier";
        public const string Name = "Breakpoint Notifier";
        public const string Description = @"Opens a dialog box in front of all other Windows to let you know that a breakpoint was hit. Great for multi-tasking!";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Coding With Calvin";
        public const string Tags = "bin,debug,folder,output";
    }
}
