// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.BreakpointNotifier.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageGuidString = "136f3004-4048-4dd9-bd6d-7ff910b2c900";
        public static Guid PackageGuid = new Guid(PackageGuidString);

        public const string CommandSetGuidString = "a12047f1-37ef-4dc0-80c3-4e3d43c5b767";
        public static Guid CommandSetGuid = new Guid(CommandSetGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int InitializeCommandId = 0x0100;
    }
}